# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Data loader for Price Sense AI
Loads product catalog, historical sales, and business rules
"""

import json
import pandas as pd
import sys
from pathlib import Path

# Add config directory to Python path
config_path = Path(__file__).parent.parent / "config"
sys.path.insert(0, str(config_path))

try:
    import business_rules
    print("✅ Successfully loaded business_rules.py")
except ImportError as e:
    print(f"⚠️ Warning: Could not import business_rules.py: {e}")
    business_rules = None


class DataLoader:
    """Centralized data loading for the application"""
    
    def __init__(self):
        self.base_path = Path(__file__).parent.parent
        self.data_path = self.base_path / "data"
        self.config_path = self.base_path / "config"
        
    def load_product_catalog(self):
        """Load product catalog from JSON"""
        try:
            # Try multiple possible filenames
            product_files = ["products.json", "product_catalog.json"]
            
            for filename in product_files:
                filepath = self.data_path / filename
                if filepath.exists():
                    print(f"✅ Loading products from: {filepath}")
                    with open(filepath, 'r') as f:
                        catalog = json.load(f)
                    products = catalog.get('products', [])
                    print(f"✅ Loaded {len(products)} products")
                    return products
            
            print(f"❌ Error: No product file found. Tried: {product_files}")
            return []
            
        except json.JSONDecodeError as e:
            print(f"❌ Error: Invalid JSON in product file: {e}")
            return []
        except Exception as e:
            print(f"❌ Error loading product catalog: {e}")
            return []
    
    def load_historical_sales(self):
        """Load historical sales data from CSV"""
        try:
            # Try multiple possible filenames
            csv_files = ["historical_data.csv", "historical_sales_2024.csv", "historical_sales.csv"]
            
            for filename in csv_files:
                filepath = self.data_path / filename
                if filepath.exists():
                    print(f"✅ Loading historical data from: {filepath}")
                    df = pd.read_csv(filepath)
                    df['date'] = pd.to_datetime(df['date'])
                    print(f"✅ Loaded {len(df)} sales records")
                    return df
            
            print(f"⚠️ Warning: No historical sales file found. Tried: {csv_files}")
            return pd.DataFrame()
            
        except Exception as e:
            print(f"⚠️ Warning: Error loading historical sales: {e}")
            return pd.DataFrame()
    
    def get_business_rules(self):
        """
        Get business rules (elasticity, cannibalization, etc.)
        Returns ALL required parameters with very lenient defaults
        """
        if business_rules is None:
            print("⚠️ Using default business rules (very lenient)")
            return self._get_default_rules()
        
        # Load all rules from business_rules module
        try:
            rules = {
                'price_elasticity': getattr(business_rules, 'PRICE_ELASTICITY', {}),
                'cannibalization_matrix': getattr(business_rules, 'CANNIBALIZATION_MATRIX', {}),
                'seasonality': getattr(business_rules, 'SEASONALITY', {}),
                'seasonality_factors': getattr(business_rules, 'SEASONALITY_FACTORS', {}),
                'duration_multipliers': getattr(business_rules, 'DURATION_MULTIPLIERS', {}),
                'discount_diminishing_returns': getattr(business_rules, 'DISCOUNT_DIMINISHING_RETURNS', {}),
                'risk_thresholds': getattr(business_rules, 'RISK_THRESHOLDS', {}),
                'risk_weights': getattr(business_rules, 'RISK_WEIGHTS', {}),
                'recommendation_thresholds': getattr(business_rules, 'RECOMMENDATION_THRESHOLDS', {}),
                'strong_yes_threshold': getattr(business_rules, 'STRONG_YES_THRESHOLD', {}),
                'maybe_threshold': getattr(business_rules, 'MAYBE_THRESHOLD', {}),
                'marketing_cost_per_unit': getattr(business_rules, 'MARKETING_COST_PER_UNIT', 0.05),
                'fixed_promotion_cost': getattr(business_rules, 'FIXED_PROMOTION_COST', 10),
                'stockout_threshold': getattr(business_rules, 'STOCKOUT_THRESHOLD', 5.0),
                'min_inventory_coverage': getattr(business_rules, 'MIN_INVENTORY_COVERAGE', 0.5),
                'min_acceptable_margin': getattr(business_rules, 'MIN_ACCEPTABLE_MARGIN', 0.05),
                'ideal_margin': getattr(business_rules, 'IDEAL_MARGIN', 0.20)
            }
            
            print("✅ Successfully loaded business rules")
            return rules
            
        except Exception as e:
            print(f"⚠️ Error loading business rules: {e}. Using defaults.")
            return self._get_default_rules()
    
    def _get_default_rules(self):
        """Return very lenient default rules"""
        return {
            'price_elasticity': {
                'Nuts': {'default': -4.0},
                'Beverages': {'default': -4.5},
                'Snacks': {'default': -4.0},
                'Confections': {'default': -4.2},
                'Dried Fruit': {'default': -3.8},
                'Breakfast': {'default': -3.9},
                'Grocery': {'default': -4.0},
                'high': {'base_lift': 4.0, 'discount_sensitivity': 6.0},
                'medium': {'base_lift': 3.5, 'discount_sensitivity': 5.0},
                'low': {'base_lift': 3.0, 'discount_sensitivity': 4.0}
            },
            'cannibalization_matrix': {
                'same_subcategory_diff_size': 0.03,
                'same_category_diff_subcategory': 0.01,
                'diff_category': 0.005
            },
            'seasonality': {'default': 1.15},
            'seasonality_factors': {'default': 1.15},
            'duration_multipliers': {7: 1.0, 14: 1.15, 21: 1.35, 28: 1.7},
            'discount_diminishing_returns': {'threshold': 70, 'reduction_factor': 0.99},
            'risk_thresholds': {
                'deep_discount': 65,
                'moderate_discount': 45,
                'high_cannibalization': 85,
                'moderate_cannibalization': 65,
                'high_lift': 300,
                'low_margin': 0.05,
                'low': 75,
                'medium': 92,
                'high': 99
            },
            'risk_weights': {
                'discount_risk': {
                    'thresholds': [
                        {'max': 45, 'score': 0},
                        {'max': 55, 'score': 1},
                        {'max': 65, 'score': 3},
                        {'max': 100, 'score': 5}
                    ]
                },
                'cannibalization_risk': {
                    'thresholds': [
                        {'max': 60, 'score': 0},
                        {'max': 75, 'score': 1},
                        {'max': 90, 'score': 3},
                        {'max': 100, 'score': 5}
                    ]
                },
                'stockout_risk': {'lift_threshold': 300, 'score': 3},
                'margin_risk': {'min_acceptable_margin': 0.05, 'score': 2}
            },
            'recommendation_thresholds': {
                'strong_yes': {'min_profit': 0.50, 'min_roi': 0.5, 'max_risk_score': 98},
                'maybe': {'min_profit': 0.01, 'min_roi': 0.01}
            },
            'strong_yes_threshold': {'min_net_profit': 0.50, 'min_roi_pct': 0.5, 'max_risk_score': 98},
            'maybe_threshold': {'min_net_profit': 0.01, 'min_roi_pct': 0.01},
            'marketing_cost_per_unit': 0.05,
            'fixed_promotion_cost': 10,
            'stockout_threshold': 5.0,
            'min_inventory_coverage': 0.5,
            'min_acceptable_margin': 0.05,
            'ideal_margin': 0.20
        }
    
    def get_product_by_id(self, product_id):
        """Get a specific product by ID"""
        products = self.load_product_catalog()
        for product in products:
            if product['id'] == product_id:
                return product
        return None
    
    def get_products_by_category(self, category):
        """Get all products in a category"""
        products = self.load_product_catalog()
        return [p for p in products if p['category'] == category]
    
    def get_product_history(self, product_id):
        """Get historical sales for a specific product"""
        df = self.load_historical_sales()
        if df.empty:
            return pd.DataFrame()
        return df[df['product_id'] == product_id].sort_values('date')


# Create singleton instance
data_loader = DataLoader()
