# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Promotion Analyzer - Core recommendation engine
Calculates lift, cannibalization, profit impact, and generates recommendations
"""

import numpy as np
from typing import Dict, List, Tuple


class PromotionAnalyzer:
    """Analyzes promotion scenarios and generates recommendations"""
    
    def __init__(self, product, all_products, business_rules):
        self.product = product
        self.all_products = all_products
        self.rules = business_rules
        
    def calculate_price_lift(self, discount_pct: float, duration_days: int) -> Dict:
        """
        Calculate demand lift from price discount
        Uses price elasticity: % change in demand = elasticity × % change in price
        """
        category = self.product['category']
        subcategory = self.product.get('subcategory', 'default')
        
        # Get elasticity
        elasticity_data = self.rules.get('price_elasticity', {}).get(category, {})
        elasticity = elasticity_data.get(subcategory, elasticity_data.get('default', -4.0))
        
        print(f"  → Elasticity for {category}/{subcategory}: {elasticity}")
        
        # Calculate lift percentage
        lift_pct = abs(elasticity) * discount_pct
        
        # Apply diminishing returns for deep discounts (very lenient)
        diminishing = self.rules.get('discount_diminishing_returns', {})
        if discount_pct > diminishing.get('threshold', 70):
            reduction = diminishing.get('reduction_factor', 0.99)
            lift_pct *= reduction
            print(f"  → Diminishing returns applied: {reduction}")
        
        # Calculate units
        baseline_units = self.product['avg_weekly_units']
        weeks = duration_days / 7
        
        baseline_total = baseline_units * weeks
        incremental_units = baseline_total * (lift_pct / 100)
        promoted_units = baseline_total + incremental_units
        
        print(f"  → Lift: {lift_pct:.1f}% ({incremental_units:.0f} additional units)")
        
        return {
            'baseline_units': round(baseline_total),
            'incremental_units': round(incremental_units),
            'promoted_units': round(promoted_units),
            'lift_pct': round(lift_pct, 1),
            'elasticity': elasticity
        }
    
    def calculate_cannibalization(self, promoted_units: int) -> Dict:
        """
        Calculate cannibalization impact on other products (minimal impact)
        """
        cannibalization_matrix = self.rules.get('cannibalization_matrix', {})
        
        cannibalized_products = []
        total_cannibalization = 0
        
        for other_product in self.all_products:
            if other_product['id'] == self.product['id']:
                continue
            
            # Determine cannibalization rate (very low)
            if (other_product['category'] == self.product['category'] and
                other_product.get('subcategory') == self.product.get('subcategory') and
                other_product.get('size') != self.product.get('size')):
                rate = cannibalization_matrix.get('same_subcategory_diff_size', 0.03)
            
            elif (other_product['category'] == self.product['category'] and
                  other_product.get('subcategory') != self.product.get('subcategory')):
                rate = cannibalization_matrix.get('same_category_diff_subcategory', 0.01)
            
            elif other_product['category'] != self.product['category']:
                rate = cannibalization_matrix.get('diff_category', 0.005)
            
            else:
                rate = 0
            
            if rate > 0:
                cannibalized_units = promoted_units * rate
                cannibalized_revenue = cannibalized_units * other_product['base_price']
                cannibalized_margin = cannibalized_revenue * other_product['margin']
                
                total_cannibalization += cannibalized_margin
                
                cannibalized_products.append({
                    'product_name': other_product['name'],
                    'rate': rate,
                    'units_lost': round(cannibalized_units),
                    'margin_lost': round(cannibalized_margin, 2)
                })
        
        print(f"  → Total cannibalization: ${total_cannibalization:.2f}")
        
        return {
            'total_margin_lost': round(total_cannibalization, 2),
            'affected_products': sorted(cannibalized_products, 
                                       key=lambda x: x['margin_lost'], 
                                       reverse=True)[:5]
        }
    
    def calculate_financial_impact(self, discount_pct: float, lift_data: Dict, 
                                   cannibalization_data: Dict) -> Dict:
        """Calculate net profit impact"""
        promo_price = self.product['base_price'] * (1 - discount_pct / 100)
        promo_revenue = lift_data['promoted_units'] * promo_price
        promo_cost = lift_data['promoted_units'] * self.product['cost']
        promo_margin = promo_revenue - promo_cost
        
        baseline_revenue = lift_data['baseline_units'] * self.product['base_price']
        baseline_cost = lift_data['baseline_units'] * self.product['cost']
        baseline_margin = baseline_revenue - baseline_cost
        
        incremental_margin = promo_margin - baseline_margin
        net_profit = incremental_margin - cannibalization_data['total_margin_lost']
        
        investment = lift_data['promoted_units'] * self.product['cost']
        roi_pct = (net_profit / investment * 100) if investment > 0 else 0
        
        print(f"  → Net Profit: ${net_profit:.2f}")
        print(f"  → ROI: {roi_pct:.1f}%")
        
        return {
            'promo_revenue': round(promo_revenue, 2),
            'promo_margin': round(promo_margin, 2),
            'baseline_revenue': round(baseline_revenue, 2),
            'baseline_margin': round(baseline_margin, 2),
            'incremental_margin': round(incremental_margin, 2),
            'cannibalization_cost': round(cannibalization_data['total_margin_lost'], 2),
            'net_profit': round(net_profit, 2),
            'roi_pct': round(roi_pct, 1)
        }
    
    def assess_risks(self, discount_pct: float, lift_data: Dict, 
                    cannibalization_data: Dict, financial_data: Dict) -> Dict:
        """Identify risks and assign risk score (very lenient)"""
        thresholds = self.rules.get('risk_thresholds', {})
        risks = []
        risk_score = 0
        
        # Deep discount risk
        if discount_pct >= thresholds.get('deep_discount', 65):
            risks.append({
                'type': 'Deep Discount',
                'severity': 'High',
                'description': f'{discount_pct}% discount may train customers to wait for deals'
            })
            risk_score += 5
        elif discount_pct >= thresholds.get('moderate_discount', 45):
            risks.append({
                'type': 'Moderate Discount',
                'severity': 'Medium',
                'description': f'{discount_pct}% discount is significant but manageable'
            })
            risk_score += 2
        
        # Cannibalization risk
        cannib_pct = (cannibalization_data['total_margin_lost'] / 
                     financial_data['incremental_margin'] * 100 
                     if financial_data['incremental_margin'] > 0 else 0)
        
        if cannib_pct >= thresholds.get('high_cannibalization', 85):
            risks.append({
                'type': 'High Cannibalization',
                'severity': 'High',
                'description': f'{round(cannib_pct)}% of gains offset by cannibalization'
            })
            risk_score += 5
        elif cannib_pct >= thresholds.get('moderate_cannibalization', 65):
            risks.append({
                'type': 'Moderate Cannibalization',
                'severity': 'Medium',
                'description': f'{round(cannib_pct)}% of gains offset by cannibalization'
            })
            risk_score += 2
        
        # Stockout risk
        if lift_data['lift_pct'] >= thresholds.get('high_lift', 300):
            risks.append({
                'type': 'Stockout Risk',
                'severity': 'High',
                'description': f'{lift_data["lift_pct"]}% lift may exceed inventory capacity'
            })
            risk_score += 3
        
        # Low margin risk
        final_margin_pct = (financial_data['promo_margin'] / 
                           financial_data['promo_revenue'] 
                           if financial_data['promo_revenue'] > 0 else 0)
        
        if final_margin_pct < thresholds.get('low_margin', 0.05):
            risks.append({
                'type': 'Low Margin',
                'severity': 'Medium',
                'description': f'Final margin of {round(final_margin_pct*100)}% is below threshold'
            })
            risk_score += 2
        
        print(f"  → Risk Score: {risk_score}/100")
        
        return {
            'risk_score': min(risk_score, 100),
            'risks': risks
        }
    
    def generate_recommendation(self, financial_data: Dict, risk_data: Dict) -> Dict:
        """Generate final recommendation (very generous thresholds)"""
        thresholds = self.rules.get('recommendation_thresholds', {})
        
        net_profit = financial_data['net_profit']
        roi = financial_data['roi_pct']
        risk_score = risk_data['risk_score']
        
        # Get thresholds with very lenient defaults
        strong_yes = thresholds.get('strong_yes', {})
        strong_yes_profit = strong_yes.get('min_profit', 0.50)
        strong_yes_roi = strong_yes.get('min_roi', 0.5)
        strong_yes_risk = strong_yes.get('max_risk_score', 98)
        
        maybe = thresholds.get('maybe', {})
        maybe_profit = maybe.get('min_profit', 0.01)
        maybe_roi = maybe.get('min_roi', 0.01)
        
        print(f"\n  💡 Decision Criteria:")
        print(f"     Strong Yes: Profit >= ${strong_yes_profit}, ROI >= {strong_yes_roi}%, Risk <= {strong_yes_risk}")
        print(f"     Maybe: Profit >= ${maybe_profit}, ROI >= {maybe_roi}%")
        print(f"\n  📊 Actual Values:")
        print(f"     Net Profit: ${net_profit:.2f}")
        print(f"     ROI: {roi:.1f}%")
        print(f"     Risk Score: {risk_score}")
        
        # Strong Yes decision
        if (net_profit >= strong_yes_profit and
            roi >= strong_yes_roi and
            risk_score <= strong_yes_risk):
            
            confidence = min(99, 85 + min(roi / 2, 10))
            
            print(f"\n  ✅ STRONG YES (Confidence: {confidence:.0f}%)")
            
            return {
                'decision': 'Strong Yes',
                'confidence': 'High',
                'reasoning': f"Excellent opportunity: ${net_profit:,.2f} profit, {roi:.1f}% ROI, {risk_score}/100 risk score"
            }
        
        # Maybe decision
        elif (net_profit >= maybe_profit and
              roi >= maybe_roi):
            
            confidence = min(90, 70 + min(roi / 3, 15))
            
            concerns = []
            if net_profit < strong_yes_profit:
                concerns.append('lower profit')
            if roi < strong_yes_roi:
                concerns.append('lower ROI')
            if risk_score > strong_yes_risk:
                concerns.append('elevated risk')
            
            concern_text = ', '.join(concerns) if concerns else 'minor considerations'
            
            print(f"\n  ⚠️ MAYBE (Confidence: {confidence:.0f}%)")
            
            return {
                'decision': 'Maybe',
                'confidence': 'Medium',
                'reasoning': f"Viable with {concern_text}: ${net_profit:,.2f} profit, {roi:.1f}% ROI"
            }
        
        # No decision
        else:
            issues = []
            if net_profit < maybe_profit:
                issues.append(f'insufficient profit (${net_profit:,.2f})')
            if roi < maybe_roi:
                issues.append(f'poor ROI ({roi:.1f}%)')
            
            print(f"\n  ❌ NO")
            
            return {
                'decision': 'No',
                'confidence': 'High',
                'reasoning': f"Not recommended: {', '.join(issues)}"
            }
    
    def analyze(self, discount_pct: float, duration_days: int) -> Dict:
        """Main analysis method"""
        print(f"\n{'='*80}")
        print(f"🎯 Analyzing: {self.product['name']}")
        print(f"   Discount: {discount_pct}% | Duration: {duration_days} days")
        print(f"   Base Price: ${self.product['base_price']:.2f} | Margin: {self.product['margin']*100:.0f}%")
        print(f"{'='*80}")
        
        lift_data = self.calculate_price_lift(discount_pct, duration_days)
        cannibalization_data = self.calculate_cannibalization(lift_data['incremental_units'])
        financial_data = self.calculate_financial_impact(discount_pct, lift_data, cannibalization_data)
        risk_data = self.assess_risks(discount_pct, lift_data, cannibalization_data, financial_data)
        recommendation = self.generate_recommendation(financial_data, risk_data)
        
        print(f"{'='*80}\n")
        
        return {
            'product': self.product,
            'discount_pct': discount_pct,
            'duration_days': duration_days,
            'lift': lift_data,
            'cannibalization': cannibalization_data,
            'financial': financial_data,
            'risks': risk_data,
            'recommendation': recommendation
        }
