# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Price Sense AI - Streamlit Application
AI-powered promotion analysis and recommendation tool
"""

import streamlit as st
import sys
from pathlib import Path
import pandas as pd

# Add modules to path
sys.path.insert(0, str(Path(__file__).parent / "modules"))

from modules.data_loader import data_loader
from modules.promotion_analyzer import PromotionAnalyzer
from modules.ai_assistant import get_ai_assistant
from modules.visualizations import *

# Page config
st.set_page_config(
    page_title="Price Sense AI",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem;
        font-weight: 700;
        color: #1e3a8a;
        margin-bottom: 0.5rem;
    }
    .sub-header {
        font-size: 1.1rem;
        color: #64748b;
        margin-bottom: 2rem;
    }
    .metric-card {
        background-color: #f8fafc;
        padding: 1.5rem;
        border-radius: 0.5rem;
        border-left: 4px solid #3b82f6;
    }
    .recommendation-card {
        padding: 2rem;
        border-radius: 0.5rem;
        margin: 1rem 0;
        text-align: center;
    }
    .dataframe {
        font-size: 0.9rem;
    }
</style>
""", unsafe_allow_html=True)


def initialize_session_state():
    """Initialize session state variables"""
    if 'analysis_result' not in st.session_state:
        st.session_state.analysis_result = None
    if 'chat_history' not in st.session_state:
        st.session_state.chat_history = []
    if 'ai_assistant' not in st.session_state:
        st.session_state.ai_assistant = get_ai_assistant()


def render_single_analysis():
    """Render the single product analysis tab"""
    # Load data
    products = data_loader.load_product_catalog()
    business_rules = data_loader.get_business_rules()
    
    if not products:
        st.error("⚠️ Could not load product catalog. Please check data files.")
        return
    
    # Sidebar - Input Configuration
    with st.sidebar:
        st.header("📊 Analysis Configuration")
        
        # Product selection
        product_names = [p['name'] for p in products]
        selected_product_name = st.selectbox(
            "Select Product",
            product_names,
            help="Choose a product to analyze"
        )
        
        selected_product = next(p for p in products if p['name'] == selected_product_name)
        
        st.markdown("---")
        
        # Discount configuration
        st.subheader("Promotion Parameters")
        
        discount_pct = st.slider(
            "Discount %",
            min_value=5,
            max_value=50,
            value=20,
            step=5,
            help="Percentage discount to offer"
        )
        
        duration_days = st.slider(
            "Duration (days)",
            min_value=7,
            max_value=28,
            value=14,
            step=7,
            help="How long the promotion will run"
        )
        
        st.markdown("---")
        
        # Product info
        st.subheader("Product Details")
        st.write(f"**Base Price:** ${selected_product['base_price']:.2f}")
        st.write(f"**Cost:** ${selected_product['cost']:.2f}")
        st.write(f"**Margin:** {selected_product['margin']*100:.0f}%")
        st.write(f"**Weekly Units:** {selected_product['avg_weekly_units']}")
        
        st.markdown("---")
        
        # Analyze button
        analyze_button = st.button("🚀 Analyze Promotion", type="primary", use_container_width=True)
    
    # Main content area
    if analyze_button:
        with st.spinner("Analyzing promotion scenario..."):
            # Run analysis
            analyzer = PromotionAnalyzer(selected_product, products, business_rules)
            result = analyzer.analyze(discount_pct, duration_days)
            st.session_state.analysis_result = result
    
    # Display results if analysis has been run
    if st.session_state.analysis_result:
        result = st.session_state.analysis_result
        
        # Recommendation Card
        rec_card = create_recommendation_card(result['recommendation'], result['financial'])
        
        st.markdown(f"""
        <div class="recommendation-card" style="background-color: {rec_card['color']}20; border: 2px solid {rec_card['color']};">
            <h1 style="color: {rec_card['color']}; margin: 0;">{rec_card['icon']} {rec_card['decision']}</h1>
            <p style="font-size: 1.2rem; margin-top: 1rem; color: #1e293b;">{rec_card['reasoning']}</p>
        </div>
        """, unsafe_allow_html=True)
        
        # Key Metrics
        st.subheader("📈 Key Metrics")
        col1, col2, col3, col4 = st.columns(4)
        
        with col1:
            st.metric(
                "Net Profit",
                f"${result['financial']['net_profit']:,.0f}",
                delta=f"${result['financial']['incremental_margin']:,.0f} incremental"
            )
        
        with col2:
            st.metric(
                "ROI",
                f"{result['financial']['roi_pct']:.1f}%"
            )
        
        with col3:
            st.metric(
                "Sales Lift",
                f"{result['lift']['lift_pct']}%",
                delta=f"+{result['lift']['incremental_units']:,} units"
            )
        
        with col4:
            st.metric(
                "Risk Score",
                f"{result['risks']['risk_score']}/100"
            )
        
        # Charts
        st.markdown("---")
        
        col1, col2 = st.columns(2)
        
        with col1:
            st.plotly_chart(
                create_financial_waterfall(result['financial'], selected_product['name']),
                use_container_width=True
            )
        
        with col2:
            st.plotly_chart(
                create_lift_comparison_chart(result['lift']),
                use_container_width=True
            )
        
        # Risk and Cannibalization
        col1, col2 = st.columns(2)
        
        with col1:
            st.plotly_chart(
                create_risk_gauge(result['risks']['risk_score']),
                use_container_width=True
            )
            
            if result['risks']['risks']:
                st.subheader("⚠️ Risk Factors")
                for risk in result['risks']['risks']:
                    severity_color = {
                        'High': '#ef4444',
                        'Medium': '#f59e0b',
                        'Low': '#10b981'
                    }.get(risk['severity'], '#64748b')
                    
                    st.markdown(f"""
                    <div style="padding: 0.75rem; margin: 0.5rem 0; background-color: {severity_color}20; 
                                border-left: 4px solid {severity_color}; border-radius: 0.25rem;">
                        <strong>{risk['type']}</strong> ({risk['severity']})<br>
                        <span style="color: #475569;">{risk['description']}</span>
                    </div>
                    """, unsafe_allow_html=True)
        
        with col2:
            cannib_chart = create_cannibalization_chart(result['cannibalization'])
            if cannib_chart:
                st.plotly_chart(cannib_chart, use_container_width=True)
        
        # Historical Data
        st.markdown("---")
        st.subheader("📊 Historical Performance")
        
        historical_df = data_loader.get_product_history(selected_product['id'])
        if not historical_df.empty:
            st.plotly_chart(
                create_historical_sales_chart(historical_df, selected_product['name']),
                use_container_width=True
            )
        else:
            st.info("No historical data available for this product.")
        
        # AI Assistant Section
        st.markdown("---")
        st.subheader("💬 AI Assistant")
        
        if st.session_state.ai_assistant:
            # Auto-generate explanation
            if not st.session_state.chat_history:
                with st.spinner("Generating AI insights..."):
                    explanation = st.session_state.ai_assistant.explain_analysis(result)
                    st.markdown(f"**AI Insights:**\n\n{explanation}")
            
            # Chat interface
            user_question = st.text_input(
                "Ask a question about this analysis:",
                placeholder="e.g., What if I increase the discount to 30%?"
            )
            
            if user_question:
                with st.spinner("Thinking..."):
                    answer = st.session_state.ai_assistant.answer_question(
                        result, 
                        user_question,
                        st.session_state.chat_history
                    )
                    
                    st.markdown(f"**Q:** {user_question}")
                    st.markdown(f"**A:** {answer}")
                    
                    # Update chat history
                    st.session_state.chat_history.append({"role": "user", "content": user_question})
                    st.session_state.chat_history.append({"role": "assistant", "content": answer})
        else:
            st.warning("⚠️ OpenAI API key not configured. Add your API key to the .env file to enable AI insights.")


def render_scenario_analyzer():
    """Render the multi-scenario analysis tab"""
    st.header("🔬 Scenario Analyzer")
    st.markdown("Test multiple discount/duration combinations to find the optimal promotion strategy.")
    
    # Load data
    products = data_loader.load_product_catalog()
    business_rules = data_loader.get_business_rules()
    
    if not products:
        st.error("⚠️ Could not load product catalog.")
        return
    
    # Configuration
    col1, col2 = st.columns([2, 1])
    
    with col1:
        product_names = [p['name'] for p in products]
        selected_product_name = st.selectbox(
            "Select Product to Analyze",
            product_names,
            key="scenario_product"
        )
        
        selected_product = next(p for p in products if p['name'] == selected_product_name)
    
    with col2:
        st.markdown("**Product Info**")
        st.write(f"Base Price: ${selected_product['base_price']:.2f}")
        st.write(f"Margin: {selected_product['margin']*100:.0f}%")
    
    st.markdown("---")
    
    # Scenario range selection
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("Discount Range")
        discount_options = st.multiselect(
            "Select discount percentages to test",
            [5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
            default=[10, 15, 20, 25, 30],
            help="Choose multiple discount levels to compare"
        )
    
    with col2:
        st.subheader("Duration Range")
        duration_options = st.multiselect(
            "Select durations (days) to test",
            [7, 14, 21, 28],
            default=[7, 14, 21],
            help="Choose multiple duration periods to compare"
        )
    
    if not discount_options or not duration_options:
        st.warning("⚠️ Please select at least one discount percentage and one duration.")
        return
    
    # Run analysis button
    if st.button("🚀 Run Scenario Analysis", type="primary", use_container_width=True):
        
        with st.spinner(f"Testing {len(discount_options) * len(duration_options)} scenarios..."):
            results = []
            
            # Run all scenarios
            for discount in discount_options:
                for duration in duration_options:
                    analyzer = PromotionAnalyzer(selected_product, products, business_rules)
                    result = analyzer.analyze(discount, duration)
                    
                    results.append({
                        'Discount %': discount,
                        'Duration (days)': duration,
                        'Net Profit ($)': round(result['financial']['net_profit'], 2),
                        'ROI (%)': round(result['financial']['roi_pct'], 1),
                        'Lift (%)': round(result['lift']['lift_pct'], 1),
                        'Risk Score': result['risks']['risk_score'],
                        'Recommendation': result['recommendation']['decision'],
                        '_result': result  # Store full result for later use
                    })
            
            # Convert to DataFrame
            df = pd.DataFrame(results)
            df_display = df.drop('_result', axis=1)
            
            # Sort by Net Profit
            df_display_sorted = df_display.sort_values('Net Profit ($)', ascending=False)
            
            # Summary metrics
            st.subheader("📊 Analysis Summary")
            
            col1, col2, col3, col4 = st.columns(4)
            
            with col1:
                st.metric("Scenarios Tested", len(df))
            
            with col2:
                strong_yes_count = len(df[df['Recommendation'] == 'Strong Yes'])
                st.metric("Strong Yes", strong_yes_count)
            
            with col3:
                best_profit = df_display['Net Profit ($)'].max()
                st.metric("Best Net Profit", f"${best_profit:,.0f}")
            
            with col4:
                best_roi = df_display['ROI (%)'].max()
                st.metric("Best ROI", f"{best_roi:.1f}%")
            
            st.markdown("---")
            
            # Results table with color coding
            st.subheader("📋 All Scenarios (Sorted by Net Profit)")
            
            # Color code recommendations
            def color_recommendation(val):
                if val == 'Strong Yes':
                    return 'background-color: #d1fae5; color: #065f46; font-weight: bold'
                elif val == 'Maybe':
                    return 'background-color: #fef3c7; color: #92400e; font-weight: bold'
                else:
                    return 'background-color: #fee2e2; color: #991b1b; font-weight: bold'
            
            # Apply styling
            styled_df = df_display_sorted.style.applymap(
                color_recommendation, 
                subset=['Recommendation']
            ).format({
                'Net Profit ($)': '${:,.2f}',
                'ROI (%)': '{:.1f}%',
                'Lift (%)': '{:.1f}%'
            })
            
            st.dataframe(styled_df, use_container_width=True, height=400)
            
            st.markdown("---")
            
            # Best scenarios
            st.subheader("🏆 Top Recommendations")
            
            tabs = st.tabs(["✅ Strong Yes", "⚠️ Maybe", "💰 Most Profitable", "📈 Best ROI"])
            
            with tabs[0]:
                strong_yes = df_display_sorted[df_display_sorted['Recommendation'] == 'Strong Yes']
                if not strong_yes.empty:
                    st.success(f"Found {len(strong_yes)} 'Strong Yes' scenarios!")
                    st.dataframe(strong_yes.head(5), use_container_width=True)
                    
                    # Highlight best
                    best = strong_yes.iloc[0]
                    st.markdown(f"""
                    **🎯 Best Strong Yes:**
                    - **{best['Discount %']}% off** for **{best['Duration (days)']} days**
                    - Net Profit: **${best['Net Profit ($)']:,.2f}**
                    - ROI: **{best['ROI (%)']}%**
                    """)
                else:
                    st.warning("No 'Strong Yes' recommendations found. Try lower discounts or shorter durations.")
            
            with tabs[1]:
                maybe = df_display_sorted[df_display_sorted['Recommendation'] == 'Maybe']
                if not maybe.empty:
                    st.info(f"Found {len(maybe)} 'Maybe' scenarios")
                    st.dataframe(maybe.head(5), use_container_width=True)
                else:
                    st.info("No 'Maybe' recommendations found.")
            
            with tabs[2]:
                top_profit = df_display_sorted.head(5)
                st.dataframe(top_profit, use_container_width=True)
                
                best = top_profit.iloc[0]
                st.markdown(f"""
                **💰 Most Profitable Scenario:**
                - **{best['Discount %']}% off** for **{best['Duration (days)']} days**
                - Net Profit: **${best['Net Profit ($)']:,.2f}**
                - Recommendation: **{best['Recommendation']}**
                """)
            
            with tabs[3]:
                top_roi = df_display_sorted.sort_values('ROI (%)', ascending=False).head(5)
                st.dataframe(top_roi, use_container_width=True)
                
                best = top_roi.iloc[0]
                st.markdown(f"""
                **📈 Best ROI Scenario:**
                - **{best['Discount %']}% off** for **{best['Duration (days)']} days**
                - ROI: **{best['ROI (%)']}%**
                - Net Profit: **${best['Net Profit ($)']:,.2f}**
                """)
            
            st.markdown("---")
            
            # Comparison charts
            st.subheader("📊 Visual Comparison")
            
            # Create comparison chart
            fig = create_scenario_comparison([r['_result'] for r in results])
            st.plotly_chart(fig, use_container_width=True)


def render_product_comparison():
    """Render the product comparison tab"""
    st.header("🏪 Product Comparison")
    st.markdown("Compare promotion performance across all products with a standard discount.")
    
    # Load data
    products = data_loader.load_product_catalog()
    business_rules = data_loader.get_business_rules()
    
    if not products:
        st.error("⚠️ Could not load product catalog.")
        return
    
    # Standard promotion parameters
    col1, col2 = st.columns(2)
    
    with col1:
        standard_discount = st.slider(
            "Standard Discount %",
            min_value=5,
            max_value=50,
            value=20,
            step=5,
            help="Apply this discount to all products"
        )
    
    with col2:
        standard_duration = st.slider(
            "Standard Duration (days)",
            min_value=7,
            max_value=28,
            value=14,
            step=7,
            help="Apply this duration to all products"
        )
    
    if st.button("🚀 Compare All Products", type="primary", use_container_width=True):
        
        with st.spinner(f"Analyzing {len(products)} products..."):
            results = []
            
            for product in products:
                analyzer = PromotionAnalyzer(product, products, business_rules)
                result = analyzer.analyze(standard_discount, standard_duration)
                
                results.append({
                    'Product': product['name'],
                    'Category': product['category'],
                    'Base Price ($)': product['base_price'],
                    'Margin (%)': product['margin'] * 100,
                    'Net Profit ($)': round(result['financial']['net_profit'], 2),
                    'ROI (%)': round(result['financial']['roi_pct'], 1),
                    'Lift (%)': round(result['lift']['lift_pct'], 1),
                    'Risk Score': result['risks']['risk_score'],
                    'Recommendation': result['recommendation']['decision']
                })
            
            df = pd.DataFrame(results)
            df_sorted = df.sort_values('Net Profit ($)', ascending=False)
            
            # Summary
            st.subheader(f"📊 Results: {standard_discount}% Off for {standard_duration} Days")
            
            col1, col2, col3, col4 = st.columns(4)
            
            with col1:
                strong_yes = len(df[df['Recommendation'] == 'Strong Yes'])
                st.metric("Strong Yes", strong_yes)
            
            with col2:
                maybe = len(df[df['Recommendation'] == 'Maybe'])
                st.metric("Maybe", maybe)
            
            with col3:
                avg_profit = df['Net Profit ($)'].mean()
                st.metric("Avg Profit", f"${avg_profit:,.0f}")
            
            with col4:
                avg_roi = df['ROI (%)'].mean()
                st.metric("Avg ROI", f"{avg_roi:.1f}%")
            
            st.markdown("---")
            
            # Results table
            def color_recommendation(val):
                if val == 'Strong Yes':
                    return 'background-color: #d1fae5; color: #065f46; font-weight: bold'
                elif val == 'Maybe':
                    return 'background-color: #fef3c7; color: #92400e; font-weight: bold'
                else:
                    return 'background-color: #fee2e2; color: #991b1b; font-weight: bold'
            
            styled_df = df_sorted.style.applymap(
                color_recommendation,
                subset=['Recommendation']
            ).format({
                'Base Price ($)': '${:.2f}',
                'Margin (%)': '{:.0f}%',
                'Net Profit ($)': '${:,.2f}',
                'ROI (%)': '{:.1f}%',
                'Lift (%)': '{:.1f}%'
            })
            
            st.dataframe(styled_df, use_container_width=True, height=500)
            
            # Category breakdown
            st.markdown("---")
            st.subheader("📈 Category Performance")
            
            category_summary = df.groupby('Category').agg({
                'Net Profit ($)': 'mean',
                'ROI (%)': 'mean',
                'Recommendation': lambda x: (x == 'Strong Yes').sum()
            }).round(2)
            
            category_summary.columns = ['Avg Net Profit ($)', 'Avg ROI (%)', 'Strong Yes Count']
            category_summary = category_summary.sort_values('Avg Net Profit ($)', ascending=False)
            
            st.dataframe(category_summary, use_container_width=True)


def main():
    initialize_session_state()
    
    # Header
    st.markdown('<div class="main-header">🎯 Price Sense AI</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Intelligent Promotion Analysis & Recommendations</div>', unsafe_allow_html=True)
    
    # Create tabs
    tab1, tab2, tab3 = st.tabs([
        "📊 Single Product Analysis",
        "🔬 Scenario Analyzer",
        "🏪 Product Comparison"
    ])
    
    with tab1:
        render_single_analysis()
    
    with tab2:
        render_scenario_analyzer()
    
    with tab3:
        render_product_comparison()


if __name__ == "__main__":
    main()
