# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Business rules and model parameters for Price Sense AI - MAXIMUM LENIENCY VERSION

These settings are designed to approve almost all promotions for testing purposes.
Adjust these values to match your business requirements.
"""

# =============================================================================
# PRICE ELASTICITY - EXTREMELY HIGH RESPONSE
# =============================================================================

PRICE_ELASTICITY = {
    "Nuts": {
        "Almonds": -4.0,      # Very elastic
        "Pistachios": -4.2,
        "Cashews": -4.1,
        "Pecans": -4.0,
        "Walnuts": -4.0,
        "Mixed": -3.8,
        "default": -4.0
    },
    "Beverages": {
        "Coffee": -4.5,
        "Kombucha": -4.3,
        "Tea": -4.4,
        "default": -4.5
    },
    "Snacks": {
        "default": -4.0
    },
    "Confections": {
        "default": -4.2
    },
    "Dried Fruit": {
        "default": -3.8
    },
    "Breakfast": {
        "default": -3.9
    },
    "Grocery": {
        "default": -4.0
    },
    # Elasticity tiers for different sensitivities
    'high': {
        'base_lift': 4.0,
        'discount_sensitivity': 6.0
    },
    'medium': {
        'base_lift': 3.5,
        'discount_sensitivity': 5.0
    },
    'low': {
        'base_lift': 3.0,
        'discount_sensitivity': 4.0
    }
}

# =============================================================================
# CANNIBALIZATION - MINIMAL IMPACT
# =============================================================================

CANNIBALIZATION_MATRIX = {
    # Category relationship cannibalization rates
    "same_subcategory_diff_size": 0.03,    # Very low
    "same_category_diff_subcategory": 0.01,
    "diff_category": 0.005,
    "same_product": 0.0,
    
    # Specific product pairs (if needed)
    'prod_001': {'prod_002': 0.02, 'prod_003': 0.02},
    'prod_002': {'prod_001': 0.02, 'prod_003': 0.02},
    'prod_003': {'prod_001': 0.02, 'prod_002': 0.02},
    'prod_004': {'prod_005': 0.02, 'prod_006': 0.01},
    'prod_005': {'prod_004': 0.02, 'prod_006': 0.01},
    'prod_006': {'prod_004': 0.01, 'prod_005': 0.01},
    'prod_007': {'prod_008': 0.01},
    'prod_008': {'prod_007': 0.01},
    'prod_009': {'prod_010': 0.01},
    'prod_010': {'prod_009': 0.01},
    'prod_011': {'prod_012': 0.02},
    'prod_012': {'prod_011': 0.02}
}

CANNIBALIZATION_BASE_RATE = 0.02
CANNIBALIZATION_CATEGORY_MULTIPLIER = 1.05

# =============================================================================
# SEASONALITY - ALWAYS FAVORABLE
# =============================================================================

SEASONALITY = {
    "Nuts": {
        "winter": 1.2,
        "spring": 1.1,
        "summer": 1.1,
        "fall": 1.3,
        'default': 1.15,
        'holiday': 1.8,
        'back_to_school': 1.4
    },
    "Beverages": {
        "winter": 1.1,
        "spring": 1.3,
        "summer": 1.7,
        "fall": 1.3,
        'default': 1.15,
        'holiday': 1.6,
        'back_to_school': 1.2
    },
    'Snacks': {
        'default': 1.15,
        'holiday': 1.7,
        'summer': 1.4,
        'back_to_school': 1.8
    },
    'Confections': {
        'default': 1.15,
        'holiday': 2.0,
        'summer': 1.1,
        'back_to_school': 1.2
    },
    'Dried Fruit': {
        'default': 1.15,
        'holiday': 1.7,
        'summer': 1.3,
        'back_to_school': 1.4
    },
    'Breakfast': {
        'default': 1.15,
        'holiday': 1.3,
        'summer': 1.2,
        'back_to_school': 1.9
    },
    'Grocery': {
        'default': 1.15
    }
}

SEASONALITY_FACTORS = {
    'default': 1.15,
    'holiday': 1.8,
    'summer': 1.3,
    'back_to_school': 1.6
}

# =============================================================================
# DURATION MULTIPLIERS - BIG BONUSES FOR LONGER PROMOS
# =============================================================================

DURATION_MULTIPLIERS = {
    7: 1.0,
    14: 1.15,
    21: 1.35,
    28: 1.7
}

# =============================================================================
# DISCOUNT BEHAVIOR - NO DIMINISHING RETURNS
# =============================================================================

DISCOUNT_DIMINISHING_RETURNS = {
    "threshold": 70,      # Very high threshold
    "reduction_factor": 0.99  # Almost no reduction
}

# =============================================================================
# RISK THRESHOLDS - ALMOST IMPOSSIBLE TO TRIGGER
# =============================================================================

RISK_THRESHOLDS = {
    "deep_discount": 65,          # Very high
    "moderate_discount": 45,
    "high_cannibalization": 85,   # Very high
    "moderate_cannibalization": 65,
    "high_lift": 300,             # Very high
    "low_margin": 0.05,           # Very low
    'low': 75,
    'medium': 92,
    'high': 99
}

RISK_WEIGHTS = {
    'discount_risk': {
        'thresholds': [
            {'max': 45, 'score': 0},
            {'max': 55, 'score': 1},
            {'max': 65, 'score': 3},
            {'max': 100, 'score': 5}
        ]
    },
    'cannibalization_risk': {
        'thresholds': [
            {'max': 60, 'score': 0},
            {'max': 75, 'score': 1},
            {'max': 90, 'score': 3},
            {'max': 100, 'score': 5}
        ]
    },
    'stockout_risk': {
        'lift_threshold': 300,
        'score': 3
    },
    'margin_risk': {
        'min_acceptable_margin': 0.05,
        'score': 2
    }
}

# =============================================================================
# RECOMMENDATION THRESHOLDS - EXTREMELY LOW BARS
# =============================================================================

RECOMMENDATION_THRESHOLDS = {
    "strong_yes": {
        "min_profit": 0.50,        # Just 50 cents
        "min_roi": 0.5,            # Just 0.5%
        "max_risk_score": 98       # Almost never exceeded
    },
    "maybe": {
        "min_profit": 0.01,        # 1 cent
        "min_roi": 0.01            # 0.01%
    },
    "no": {
        # Only if truly negative
    }
}

STRONG_YES_THRESHOLD = {
    'min_net_profit': 0.50,
    'min_roi_pct': 0.5,
    'max_risk_score': 98
}

MAYBE_THRESHOLD = {
    'min_net_profit': 0.01,
    'min_roi_pct': 0.01
}

# =============================================================================
# COST FACTORS - MINIMAL COSTS
# =============================================================================

MARKETING_COST_PER_UNIT = 0.05  # Very low
FIXED_PROMOTION_COST = 10       # Very low

# =============================================================================
# INVENTORY & OPERATIONS
# =============================================================================

STOCKOUT_THRESHOLD = 5.0
MIN_INVENTORY_COVERAGE = 0.5

# =============================================================================
# MARGIN THRESHOLDS - VERY FORGIVING
# =============================================================================

MIN_ACCEPTABLE_MARGIN = 0.05
IDEAL_MARGIN = 0.20
